[project]
name = "bib-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "scipy>=1.15.3",
    "tqdm>=4.67.1",
    "ultralytics>=8.3.143",
]

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
]
